version: '3'
services:
  goldsprints:
    image: goldsprints:latest
    build: .
    hostname: goldsprints   
    restart: unless-stopped
    expose:
      - "8080:8000"
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
